
import java.awt.Color;
import java.security.SecureRandom;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    ArrayList<JLabel> Etiquetas = new ArrayList();
    SecureRandom numeroAleatorio = new SecureRandom();
    String[] picFacil = new String[8];
    String[][] rutaFacil = new String[4][4];
    int[] nums = new int[8];
    int cantClics = 0;
    String [] Comparacion = new String [2];
    int [] numeroCarta = new int [2];
    int aciertos=0;
    int fallas=0;
    

    public Interfaz() {
        initComponents();
        setSize(800, 700);
        setLocationRelativeTo(this);
        cargarEtiqutas();
        agregarImagenes();
        plnFacil.setVisible(false);
        btnComparar.setEnabled(false);
    }

    void cargarEtiqutas() {
        Etiquetas.add(jlbF1);
        Etiquetas.add(jlbF2);
        Etiquetas.add(jlbF3);
        Etiquetas.add(jlbF4);
        Etiquetas.add(jlbF5);
        Etiquetas.add(jlbF6);
        Etiquetas.add(jlbF7);
        Etiquetas.add(jlbF8);
        Etiquetas.add(jlbF9);
        Etiquetas.add(jlbF10);
        Etiquetas.add(jlbF11);
        Etiquetas.add(jlbF12);
        Etiquetas.add(jlbF13);
        Etiquetas.add(jlbF14);
        Etiquetas.add(jlbF15);
        Etiquetas.add(jlbF16);
    }

    public int numerosImagen() {
        int numeroGenerado = numeroAleatorio.nextInt(8);
        return numeroGenerado;
    }

    void agregarImagenes() {
        for (int pic = 0; pic < picFacil.length; pic++) {
            picFacil[pic] = "/img/" + (pic + 1) + ".jpeg";

        }
    }

    void cargarImagenesEtiquetas() {
        int contador = 0;

        for (int fila = 0; fila < rutaFacil.length; fila++) {
            for (int colupna = 0; colupna < rutaFacil[0].length; colupna++) {
                int temp = numerosImagen();
                if (nums[temp] == 2) {
                    colupna--;

                } else {
                    rutaFacil[fila][colupna] = picFacil[temp];
                    nums[temp]++;
                }

            }

        }

        for (int fila = 0; fila < rutaFacil.length; fila++) {
            for (int colupna = 0; colupna < rutaFacil[0].length; colupna++) {
                Etiquetas.get(contador).setOpaque(true);
                Etiquetas.get(contador).setIcon(new ImageIcon(getClass().getResource(rutaFacil[fila][colupna])));
                Etiquetas.get(contador).setText("" + (contador + 1));
                contador++;
            }
        }
    }

    void voltearCartas() {
        for (int i = 0; i < Etiquetas.size(); i++) {
            Etiquetas.get(i).setIcon(null);
            Etiquetas.get(i).setBackground(Color.BLACK);
        }
    }

    void mostrarImagen(int numCarta) {
        if (cantClics != 2) {
            if (numCarta >= 0 && numCarta <= 3) {
                Comparacion[cantClics]= rutaFacil[0][numCarta];
                Etiquetas.get(numCarta).setIcon(new ImageIcon(getClass().getResource(rutaFacil[0][numCarta])));
            } else if (numCarta >= 4 && numCarta <= 7) {
                Comparacion[cantClics]= rutaFacil[1][numCarta-4];
                Etiquetas.get(numCarta).setIcon(new ImageIcon(getClass().getResource(rutaFacil[1][numCarta - 4])));
            } else if (numCarta >= 8 && numCarta <= 11) {
                Comparacion[cantClics]= rutaFacil[2][numCarta-8];
                Etiquetas.get(numCarta).setIcon(new ImageIcon(getClass().getResource(rutaFacil[2][numCarta - 8])));
            } else {
                Comparacion[cantClics]= rutaFacil[3][numCarta-12];
                Etiquetas.get(numCarta).setIcon(new ImageIcon(getClass().getResource(rutaFacil[3][numCarta - 12])));
            }
            numeroCarta[cantClics]=numCarta; 
            cantClics++;
            if (cantClics==2){
                btnComparar.setEnabled(true);
            }
        }
    }

    /**
     * zz This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFacil = new javax.swing.JButton();
        plnFacil = new javax.swing.JPanel();
        jlbF1 = new javax.swing.JLabel();
        jlbF2 = new javax.swing.JLabel();
        jlbF3 = new javax.swing.JLabel();
        jlbF4 = new javax.swing.JLabel();
        jlbF5 = new javax.swing.JLabel();
        jlbF6 = new javax.swing.JLabel();
        jlbF7 = new javax.swing.JLabel();
        jlbF8 = new javax.swing.JLabel();
        jlbF9 = new javax.swing.JLabel();
        jlbF10 = new javax.swing.JLabel();
        jlbF11 = new javax.swing.JLabel();
        jlbF12 = new javax.swing.JLabel();
        jlbF13 = new javax.swing.JLabel();
        jlbF14 = new javax.swing.JLabel();
        jlbF15 = new javax.swing.JLabel();
        jlbF16 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnComparar = new javax.swing.JButton();
        jlbFallas = new javax.swing.JLabel();
        jlbAciertos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnFacil.setText("Mostrar Tablero");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacil);
        btnFacil.setBounds(30, 20, 590, 30);

        plnFacil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        plnFacil.setLayout(null);

        jlbF1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF1MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF1);
        jlbF1.setBounds(27, 14, 81, 69);

        jlbF2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF2MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF2);
        jlbF2.setBounds(126, 14, 81, 69);

        jlbF3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF3MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF3);
        jlbF3.setBounds(231, 14, 81, 69);

        jlbF4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF4MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF4);
        jlbF4.setBounds(330, 14, 81, 69);

        jlbF5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF5MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF5);
        jlbF5.setBounds(27, 89, 81, 69);

        jlbF6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF6MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF6);
        jlbF6.setBounds(126, 89, 87, 69);

        jlbF7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF7MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF7);
        jlbF7.setBounds(231, 89, 81, 69);

        jlbF8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF8MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF8);
        jlbF8.setBounds(330, 89, 81, 69);

        jlbF9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF9MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF9);
        jlbF9.setBounds(27, 170, 81, 69);

        jlbF10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF10MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF10);
        jlbF10.setBounds(126, 170, 81, 69);

        jlbF11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF11MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF11);
        jlbF11.setBounds(231, 170, 81, 69);

        jlbF12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF12MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF12);
        jlbF12.setBounds(330, 170, 81, 69);

        jlbF13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF13MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF13);
        jlbF13.setBounds(33, 257, 81, 69);

        jlbF14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF14MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF14);
        jlbF14.setBounds(132, 257, 81, 69);

        jlbF15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF15MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF15);
        jlbF15.setBounds(231, 257, 81, 69);

        jlbF16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbF16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF16MouseClicked(evt);
            }
        });
        plnFacil.add(jlbF16);
        jlbF16.setBounds(330, 257, 81, 69);

        getContentPane().add(plnFacil);
        plnFacil.setBounds(90, 120, 470, 350);

        btnJugar.setText("Mostrar/Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(630, 80, 120, 30);

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });
        getContentPane().add(btnComparar);
        btnComparar.setBounds(630, 150, 100, 24);

        jlbFallas.setBorder(javax.swing.BorderFactory.createTitledBorder("Fallas"));
        getContentPane().add(jlbFallas);
        jlbFallas.setBounds(630, 370, 130, 110);

        jlbAciertos.setBorder(javax.swing.BorderFactory.createTitledBorder("Aciertos"));
        getContentPane().add(jlbAciertos);
        jlbAciertos.setBounds(630, 220, 130, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        // TODO add your handling code here:
        plnFacil.setVisible(true);
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
        
        if (Comparacion[0].equals(Comparacion[1])){
            Etiquetas.get(numeroCarta[0]) .setVisible(false);
            Etiquetas.get(numeroCarta[1]) .setVisible(false);
            JOptionPane.showMessageDialog(null, "Es correcto");
            aciertos++;
            jlbAciertos.setText(""+aciertos);
    }else {
            fallas++;
            jlbFallas.setText(""+fallas);
            voltearCartas();
        }
        btnComparar.setEnabled(false);
        cantClics=0;
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        if (rutaFacil[0][0] == null) {
            cargarImagenesEtiquetas();
            btnJugar.setText("Jugar");
        } else {
            voltearCartas();
            btnJugar.setText("Jugando");
        }

    }//GEN-LAST:event_btnJugarActionPerformed

    private void jlbF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF1MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF1.getText()) - 1);
    }//GEN-LAST:event_jlbF1MouseClicked

    private void jlbF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF2MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF2.getText()) - 1);
    }//GEN-LAST:event_jlbF2MouseClicked

    private void jlbF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF3MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF3.getText()) - 1);
    }//GEN-LAST:event_jlbF3MouseClicked

    private void jlbF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF4MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF4.getText()) - 1);
    }//GEN-LAST:event_jlbF4MouseClicked

    private void jlbF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF5MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF5.getText()) - 1);
    }//GEN-LAST:event_jlbF5MouseClicked

    private void jlbF6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF6MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF6.getText()) - 1);
    }//GEN-LAST:event_jlbF6MouseClicked

    private void jlbF7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF7MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF7.getText()) - 1);
    }//GEN-LAST:event_jlbF7MouseClicked

    private void jlbF8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF8MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF8.getText()) - 1);
    }//GEN-LAST:event_jlbF8MouseClicked

    private void jlbF9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF9MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF9.getText()) - 1);
    }//GEN-LAST:event_jlbF9MouseClicked

    private void jlbF10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF10MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF10.getText()) - 1);
    }//GEN-LAST:event_jlbF10MouseClicked

    private void jlbF11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF11MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF11.getText()) - 1);
    }//GEN-LAST:event_jlbF11MouseClicked

    private void jlbF12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF12MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF12.getText()) - 1);
    }//GEN-LAST:event_jlbF12MouseClicked

    private void jlbF13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF13MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF13.getText()) - 1);
    }//GEN-LAST:event_jlbF13MouseClicked

    private void jlbF14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF14MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF14.getText()) - 1);
    }//GEN-LAST:event_jlbF14MouseClicked

    private void jlbF15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF15MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF15.getText()) - 1);
    }//GEN-LAST:event_jlbF15MouseClicked

    private void jlbF16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF16MouseClicked
        // TODO add your handling code here:
        mostrarImagen(Integer.parseInt(jlbF16.getText()) - 1);
    }//GEN-LAST:event_jlbF16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jlbAciertos;
    private javax.swing.JLabel jlbF1;
    private javax.swing.JLabel jlbF10;
    private javax.swing.JLabel jlbF11;
    private javax.swing.JLabel jlbF12;
    private javax.swing.JLabel jlbF13;
    private javax.swing.JLabel jlbF14;
    private javax.swing.JLabel jlbF15;
    private javax.swing.JLabel jlbF16;
    private javax.swing.JLabel jlbF2;
    private javax.swing.JLabel jlbF3;
    private javax.swing.JLabel jlbF4;
    private javax.swing.JLabel jlbF5;
    private javax.swing.JLabel jlbF6;
    private javax.swing.JLabel jlbF7;
    private javax.swing.JLabel jlbF8;
    private javax.swing.JLabel jlbF9;
    private javax.swing.JLabel jlbFallas;
    private javax.swing.JPanel plnFacil;
    // End of variables declaration//GEN-END:variables

    private void cargarEtiquetas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
